import Head from 'next/head'
import Image from 'next/image'
import Button from '../components/Button'
import Radio from '../components/Radio'
import RadioBox from '../components/RadioBox'
import Check from '../components/Check'
import styles from '../styles/Home.module.css'
// import styles from '../styles/button.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.button}>
          <Button text={"Button disabled"} disabled={true}></Button>
          <Button text={"Button enabled"} disabled={false}></Button>
      </div>
      <div className={styles.radio}>
         <Radio text={'Переключатель 1'} id={"r1"}></Radio>
         <Radio text={'Переключатель 2 disabled true'} id={"r2"} disabled={true}></Radio>
      </div>
      <div className={styles.check}>
        <Check label={'Check 1'} id={"ch1"}></Check>
        <Check label={'Check 2 disabled true'} id={"ch2"} disabled={true}></Check>
      </div>
     
      {/* <Check></Check> */}
    </div>
  )
}
